name: maven build sonar

on:
   workflow_dispatch 


env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Java jdk setup
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: maven target # change accordingly
      run: mvn clean install
      
    - name: Perform analysis on Sonar Qube
      uses: SonarSource/sonarcloud-github-action@v1.9.1
      with:
        sonarcloud.organization: "harshakp06"
        sonarcloud.projectKey: "harshakp06_spring-petclinic"
        sonarcloud.projectName: "spring-petclinic"
        sonarcloud.token: ${{ env.SONAR_TOKEN }}
        sonarcloud.scannerVersion: "4.2.0.1873"



